### ISSUE TITLE
Weird behavior with must

### ISSUE THREAD

**Issue by julien-f** [AndreasMadsen/stack-chain#12]
Yep, me again :stuck_out_tongue: 

```js
require('stack-chain')
var expect = require('must')

expect(
  Promise.reject({})
).to.reject.to.be.an.object().catch(function (error) {
  console.error(error.stack)
})
```

Output:

```
TypeError: Function.prototype.toString is not generic
    at Must.toString (native)
    at StackFormater.FormatStackTrace [as _formater] (/tmp/node_modules/stack-chain/format.js:30:20)
    at Function.prepareStackTrace (/tmp/node_modules/stack-chain/stack-chain.js:138:29)
    at Must.assert (/tmp/node_modules/must/lib/thenable.js:20:41)
    at apply (/tmp/node_modules/lodash._createwrapper/index.js:72:25)
    at Must.wrapper (/tmp/node_modules/lodash._createwrapper/index.js:415:12)
    at Must.object (/tmp/node_modules/must/must.js:326:8)
    at Must.exports.then (/tmp/node_modules/must/lib/thenable.js:26:6)
    at runMicrotasksCallback (node.js:322:7)
    at nextTickCallbackWith0Args (node.js:415:9)
```

- it works correctly without importing stack-chain
- it prints the correct error if the test fails
- for info: Node 4.3.1 and npm 3.7.1

@moll, any insights?

**Comment by AndreasMadsen** [comment]
I'm so exited about debugging this, I have absolutely no clues. Unfortunately it will be a few days before I get the time.

> Yep, me again

haha. It is amazing how you can find the oddest conflicts. But I truly want `trace` to be super stable and you are a really big help.

**Comment by julien-f** [comment]
No worries, I am in no hurry :)

> haha. It is amazing how you can find the oddest conflicts. But I truly want trace to be super stable and you are a really big help.

It's the least as could do as a happy user! ;)

**Comment by AndreasMadsen** [comment]
Alright I have reduced it to the following, but I still don't have any clues about where the error is coming from:

```javascript
//
// Helpers
//
var defineGetter = function(obj, name, fn) {
 return Object.defineProperty(obj, name, { get: fn })
}

var defineSetter = function(obj, name, fn) {
 return Object.defineProperty(obj, name, { set: fn })
}

var wrap = require("lodash.wrap")
var lookupGetter = Object.prototype.__lookupGetter__

//
// Thenable
//
function Thenable(must, promisify) {
  must = Object.create(must)

  for (var name in must)
    if (hasFunction(must, name)) must[name] = promisify(must[name])

  Object.defineProperty(must, "assert", {
    value: wrap(must.assert, Thenable.prototype.assert),
    configurable: true, writable: true
  })

  return must
}

Thenable.prototype.assert = function assert(orig, ok, msg, opts) {
  opts = opts ? Object.create(opts) : {}
  if ("stack" in this) opts.stack = this.stack
  orig.call(this, ok, msg, opts)
}

var then = Thenable.prototype.then = function(fn, args, actual) {
  this.actual = actual
  fn.apply(this, args)
}

function hasFunction(obj, name) {
  return !lookupGetter(obj, name) && typeof obj[name] == "function"
}

//
// Rejectable
//
function Rejectable(must) {
  return Thenable(must, promisify)
}
module.exports = Rejectable;

function promisify(fn) {
  return function() {
    var self = Object.create(this)
    if (Error.captureStackTrace) Error.captureStackTrace(self, arguments.callee)
    return this.actual.then(raise, then.bind(self, fn, arguments))
  }
}

function raise() {  }

//
// Chain
//
function chain(self, fn) {
  var assert = fn.bind(self)
  assert.apply = fn.apply
  assert.bind = fn.bind
  assert.call = fn.call
  assert.toString = fn.toString
  Object.setPrototypeOf(assert, self)

  return assert
}

//
// Must
//
function Must(actual, message) {
  if (!(this instanceof Must)) return new Must(actual, message)
  this.actual = actual
  if (message != null) this.message = message
}
module.exports = Must

defineGetter(Must.prototype, "an", function() {
  return chain(this, this.instanceof)
});

defineGetter(Must.prototype, "be", function() {
  return chain(this, this.equal)
})

defineGetter(Must.prototype, "to", passthrough)

Must.prototype.object = function() {
  var ok = this.actual && typeof this.actual == "object"
  this.assert(ok, "be an object")
}

Must.prototype.instanceof = function(expected) {
  var ok = this.actual instanceof expected
  this.assert(ok, instanceofMessage.bind(this, expected), {expected: expected})
}

function instanceofMessage(expected) {
  var type = expected.displayName || expected.name || stringify(expected)
  return "be an instance of " + type
}

Must.prototype.instanceOf = Must.prototype.instanceof

Must.prototype.equal = function(expected) {
  this.assert(this.actual === expected, "equal", {expected: expected})
}

defineGetter(Must.prototype, "reject", function() {
  return Rejectable(this)
})

function passthrough() { return this }

//
// Test
//
require('stack-chain');
new Must(
  Promise.reject({})
).to.reject.to.be.an.object().catch(function (error) {
  console.error(error.stack)
})
```

**Comment by AndreasMadsen** [comment]
Second reduction, it appears to be some combination of `Error.captureStackTrace`, overwriting the `toString` and accessing `.stack`. But I'm still looking.

```javascript
//
// Thenable
//
function Thenable(must) {
  must = Object.create(must)

  for (var name in must) {
    if (typeof must[name] == "function") {
      must[name] = promisify(must[name])
    }
  }

  return must
}

function promisify(fn) {
  return function cut() {
    var self = Object.create(this)
    Error.captureStackTrace(self, cut)
    return this.actual.catch(fn.bind(self))
  }
}

//
// Must
//
function Must(actual) {
  this.actual = actual
}

Object.defineProperty(Must.prototype, "an", { get: function() {
  var assert = this.instanceof.bind(this)
  assert.toString = this.instanceof.toString
  Object.setPrototypeOf(assert, this)
  return assert
}});

Must.prototype.object = function() {
  this.stack;
}

Must.prototype.instanceof = function(expected) {
  this.stack;
}

Must.prototype.reject = function () {
  return Thenable(this);
}

//
// Test
//
require('stack-chain');
new Must(
  Promise.reject({})
).reject().an.object().catch(function (error) {
  console.error(error.stack)
})
```

**Comment by moll** [comment]
If it's of any help, but I think you all did noticed already, that Must.js saves and later shows the stack to the `then` access (`foo.must.then`). Stack manipulation isn't particularly pure, but was a way to get at least somewhat of a useful assertion failure trace.

**Comment by AndreasMadsen** [comment]
@moll Yes, but that shouldn't cause any trouble for stack-chain.

**Comment by AndreasMadsen** [comment]
Okay this is my final reduction:

```javascript
'use strict';
require('stack-chain');

var an = function () {}
an.toString = an.toString // originally not an, but still a cause of failure
Object.setPrototypeOf(an, {}); // Set prototype of a function to an object

var self = Object.create(an); // prototype wrap an
Error.captureStackTrace(self); // prepears .stack
console.log(self.stack); // calling .stack will invoke stack-chain
```

What happens is that `Error.captureStackTrace` makes `self` pseudo-error object. This means that a `.stack` will be set. This property is _v8-magic_ and is lazy calculated by v8.

Once `self.stack` is accessed, the stack-chain machinery starts. The important part here is in the [formatter](https://github.com/AndreasMadsen/stack-chain/blob/9dcfd1399b0ab3f88db7a19db6f5af3c9340e341/format.js).

This formatter calls `error.toString()` which is now `an.toString()`. This has obviously nothing to do with an error, but is `Function.prototype.toString`. 

This is actually a security issue! The `self.stack` will print out code from the program and perhaps reveal sensitive information. Thus v8 throws `TypeError: Function.prototype.toString is not generic` to prevent this. Note that if `an.toString = an.toString` where removed, `an.toString` becomes `Object.prototype.toString` and just returns `[object Object]`, this is a safe operation thus v8 doesn't throw.

The question is now why it works without `stack-chain`. The answer is that the `stack-chain` formatter which where originally copied from v8 is slightly outdated. The [internal formatter](https://github.com/v8/v8/blob/b16fc86389c3cafa76a53744d1bacd756ec528cb/src/js/messages.js#L815) now calls an internal function `FormatErrorString`:

```javascript
function FormatErrorString(error) {
  try {
    return %_Call(ErrorToString, error);
  } catch (e) {
    try {
      return "<error: " + e + ">";
    } catch (ee) {
      return "<error>";
    }
  }
}
```

`%_Call(ErrorToString, error);` is basically the same as `Error.prototype.toString.call(error)` except that `Error.prototype.toString` can be overwritten and `ErrorToString` can't. Updating the stack-chain formatter to use `FormatErrorString` should thus solve the issue.

@julien-f Can I get you to test the solution using this branch: https://github.com/AndreasMadsen/stack-chain/tree/debug-issue-12 - I'm not exactly sure what the expected result is, as I have never used `must`.

**Comment by AndreasMadsen** [comment]
For history this where the sequenced version of my second reduction:

```javascript
'use strict';
require('stack-chain');

var expect = {
  actual: Promise.reject({}),
  object: function () {
    this.stack
  }
};

var reject = Object.create(expect)
var objectFn = reject.object;
reject.object = function cut() {
  var self = Object.create(this)
  Error.captureStackTrace(self, cut)
  return this.actual.catch(objectFn.bind(self))
};

var an = reject.object.bind(reject)
an.toString = reject.object.toString
Object.setPrototypeOf(an, reject)

var object = an.object();

object.catch(function (error) {
  console.error(error.stack)
});
```

**Comment by julien-f** [comment]
Thanks for all this work :)

My example is now working but [my original](https://github.com/julien-f/js-promise-toolbox/blob/stack-chain-issue-12/src/index.spec.js#L60-L74) is [still here](https://travis-ci.org/julien-f/js-promise-toolbox/jobs/115855937), I'll have to investigate.

**Comment by AndreasMadsen** [comment]
Looks like [`source-map-support` is calling `error.toString()` implicitly](https://github.com/evanw/node-source-map-support/blob/master/source-map-support.js#L357), that won't work it should at least be `Error.prototype.toString.call(error)`, however the reality is far more complicated.

**Comment by julien-f** [comment]
Hmm, I see…

I think the problem meets issue #7 where it was suggested that stack-chain could provide some utilities to ease altering stack traces because there seem to be a lot of edge cases.

**Comment by AndreasMadsen** [comment]
The issue is really about `error.toString()` and not `callSite.toString()` which is what #7 is about. 

But I guess there is some connection. If `node-source-map-support` used `stack-chain` then the `non-generic` issue would be fixed, and if `stack-chain` provided utilities for creating a custom `CallSite` objective the incentive for using `stack-chain` might be bigger.

**Comment by AndreasMadsen** [comment]
Version 1.3.7 is published

**Comment by julien-f** [comment]
I have a simple implementation of `source-map-support` based on `stack-chain` [there](https://github.com/julien-f/js-source-map-support-2) if you are interested.

I have not yet introduced it to the `source-map-support` community because I don't have time to take care of this currently but it might be interesting.
