### ISSUE TITLE
ugilify support

### ISSUE THREAD

**Issue by charlierudolph** [AndreasMadsen/stack-chain#5]
Trying to browserify the package and hit the error
```
'return' outside of function while parsing file
```

**Comment by charlierudolph** [comment]
Sorry this comes from trying to uglify.

**Comment by AndreasMadsen** [comment]
That sounds like an issue with uglify not stack-chain. Try and browserify before uglify, then the `return` statement should be inside a function.

**Comment by AndreasMadsen** [comment]
Fixed by #6
